unbind connection factory should use surround with try & finally
freenowtech/spring-multirabbit pull request #24
Opened 2020-11-04 06:54 UTC by WEIZIBIN

Unbind connection factory should use surround with try & finally.

When the exception occurs before unbind(), the thread does not clean up the bind resources, and there will be routing to the old resources or java.lang.IllegalArgumentException exceptions when next bind() call.

```
14:52:54.493 "http-nio-30111-exec-3" INFO  "d16b7c802978d8b7" "d16b7c802978d8b7" "" com.heytea.starter.autoconfigure.config.BaseGlobalExceptionHandler 
java.lang.IllegalArgumentException: Already value [internal-system] for key [org.springframework.amqp.rabbit.connection.SimpleRoutingConnectionFactory@62e0f621] bound to thread [http-nio-30111-exec-3]
	at org.springframework.util.Assert.isNull(Assert.java:176)
	at org.springframework.amqp.rabbit.connection.SimpleResourceHolder.bind(SimpleResourceHolder.java:133)
        ...
```

2020-12-03 23:47 UTC, emreugurel commented
If write 
SimpleResourceHolder.unbindIfPossible(rabbitTemplate.getConnectionFactory()); 
before 
SimpleResourceHolder.bind(rabbitTemplate.getConnectionFactory(), CONNECTION_PREFIX + id);
It will solve this problem. No need your code.

2020-12-29 15:35 UTC, rwanderc commented
As I can see, this is only changing the examples and README.
It's also possible to use the `ConnectionFactoryContextWrapper` provided in this library, which wraps this logic inside.
That's ok for the instructional purpose. Thanks for your contribution.

2020-12-31 01:01 UTC, rwanderc requested changes

2021-01-24 18:52 UTC, rwanderc approved these changes
Thank you @WEIZIBIN

2021-01-24 18:56 UTC, merged