Added compatibility to Spring Boot v2.5.0
freenowtech/spring-multirabbit pull request #74
Opened 2022-02-16 09:51 UTC by canarddemagret

It's the same PR than [lhmoraes](https://github.com/lhmoraes), but with codestyle and tests done.

2022-04-16 11:04 UTC, ArtemchukAndrei94 commented
Hello. I want you to add compatibility with spring boot 2.5.0. Please check this pull request and if everything is ok, merge with main. Thanks.

2022-04-17 14:53 UTC, rwanderc commented
Thank you for your contribution @canarddemagret.
The PR looks good, just a few formatting comments.
Please also update the SpringBoot version of the examples, so it's aligned with the project and fix the build.

2022-04-17 14:54 UTC, rwanderc approved these changes

2022-04-17 14:54 UTC, rwanderc commented on spring-multirabbit/src/main/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitAutoConfiguration.java
> +                final ObjectProvider<ConnectionFactoryCustomizer> connectionFactoryCustomizers) throws Exception {
I think it should be `connectionFactoryCustomizer` without `s`, right?

2022-04-17 14:54 UTC, rwanderc commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +    private ObjectProvider<ConnectionFactoryCustomizer> connectionFactoryCustomizers;
Also the plural comment here.

2022-04-17 14:54 UTC, rwanderc commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +                connectionFactoryCustomizers)).thenReturn(new CachingConnectionFactory());
you can use the previous line as much as possible, and leave only .thenReturn(...); at the new line.

2022-04-17 14:54 UTC, rwanderc commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +                connectionFactoryCustomizers)).thenReturn(new CachingConnectionFactory());
you can use the previous line as much as possible, and leave only .thenReturn(...); at the new line.

2022-04-17 14:55 UTC, rwanderc requested changes
Thank you for your contribution @canarddemagret.
The PR looks good, just a few formatting comments.
Please also update the SpringBoot version of the examples, so it's aligned with the project and fix the build.

2022-04-18 07:40 UTC, ArtemchukAndrei94 commented
Hello. I created it myself pr
https://github.com/freenowtech/spring-multirabbit/pull/84, check review
please. Thanks.

вс, 17 апр. 2022 г. в 17:55, Wander Costa ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Thank you for your contribution @canarddemagret
> <https://github.com/canarddemagret>.
> The PR looks good, just a few formatting comments.
> Please also update the SpringBoot version of the examples, so it's aligned
> with the project and fix the build.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/freenowtech/spring-multirabbit/pull/74#pullrequestreview-943957778>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIMFDTDAZEUGWND7JP5G3BLVFQQ7XANCNFSM5ORCRFJQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-04-18 11:16 UTC, ArtemchukAndrei94 commented
I suggest waiting a few days for canarddemagret, and if he is not active, I suggest returning my pr and looking at it and if canarddemagret contacts and makes corrections, that will be fine too. Thanks.

2022-04-18 11:28 UTC, canarddemagret commented
I am currently in holiday, I will be able to finish the PR friday

2022-04-18 11:28 UTC, rwanderc commented
> I suggest waiting a few days for canarddemagret, and if he is not active, I suggest returning my pr and looking at it and if canarddemagret contacts and makes corrections, that will be fine too. Thanks.

@canarddemagret's PR was missing only a few minor changes. I'm proceeding with the fixes on @canarddemagret PR so as to push this to the main branch and eventually release the 2.5.0.

2022-04-18 11:31 UTC, rwanderc approved these changes

2022-04-18 11:35 UTC, merged

2022-04-18 12:38 UTC, ArtemchukAndrei94 commented
Thank you so much!