Feature/spring-boot-260
freenowtech/spring-multirabbit pull request #76
Opened 2022-04-06 07:02 UTC by JiHyunSim

Added compatibility to Spring Boot v2.6.0

2022-04-19 07:26 UTC, rwanderc requested changes
Thank you for your contribution @JiHyunSim. It looks good overall, but you missed paying attention to the checkstyle issues (imports, missing spaces, lengthy lines). It's not building (run `mvn clean install`) due to these errors.
Could you pls fix them and update the PR?

2022-04-19 07:26 UTC, rwanderc commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +import org.springframework.amqp.rabbit.connection.*;
Pls, keep the imports ungrouped

2022-04-19 07:26 UTC, rwanderc commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Pls, keep the imports ungrouped

2022-04-19 07:26 UTC, rwanderc commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Pls, keep the imports ungrouped

2022-04-19 07:26 UTC, rwanderc commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +import static org.mockito.Mockito.*;
Pls, keep the imports ungrouped

2022-04-19 07:26 UTC, rwanderc commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +import static org.mockito.Mockito.*;
Pls, keep the imports ungrouped

2022-04-20 02:59 UTC, JiHyunSim commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
ok

2022-04-20 02:59 UTC, JiHyunSim commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
ok

2022-04-20 02:59 UTC, JiHyunSim commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +import static org.mockito.Mockito.*;
ok

2022-04-20 02:59 UTC, JiHyunSim commented on spring-multirabbit/src/test/java/org/springframework/boot/autoconfigure/amqp/MultiRabbitConnectionFactoryCreatorTest.java
> +import static org.mockito.Mockito.*;
ok

2022-04-22 07:17 UTC, rwanderc commented
@JiHyunSim thank you for the changes.
But the build is still broken.

2022-04-22 07:17 UTC, rwanderc requested changes
Needs the fix of the build

2022-04-22 19:52 UTC, rwanderc approved these changes

2022-04-22 19:52 UTC, merged